//for JobList
export const ITEMS_HAS_ERRORED='ITEMS_HAS_ERRORED';
export const ITEMS_IS_LOADING='ITEMS_IS_LOADING';
export const ITEMS_FETCH_DATA_SUCCESS='ITEMS_FETCH_DATA_SUCCESS';

//for jobDetails
export const   ITEM_DETAILS_HAS_ERRORED="ITEM_DETAILS_HAS_ERRORED"
export const   ITEM_DETAILS_IS_LOADING='ITEM_DETAILS_IS_LOADING'
export const   ITEM_DETAILS_FETCH_DATA_SUCCESS='ITEM_DETAILS_FETCH_DATA_SUCCESS'

//current url
export const CURRENT_URL="CURRENT_URL"

//dark mode
export const DARK_MODE_TOGGLE="DARK_MODE_TOGGLE"

// Pagination api call
export const PAGINATION_ITEMS_HAS_ERRORED='PAGINATION_ITEMS_HAS_ERRORED';
export const PAGINATION_ITEMS_IS_LOADING='PAGINATION_ITEMS_IS_LOADING';
export const PAGINATION_ITEMS_FETCH_DATA_SUCCESS='PAGINATION_ITEMS_FETCH_DATA_SUCCESS';

//Set Latitude, longitude if permitted
export const SET_LOCATION_CORS='SET_LOCATION_CORS'

